### PR TITLE
Migrate Piglet to multitaget package

### PR DESCRIPTION
**Pull request by harrison314**
Migrate Piglet to .netstandard1.6, .netstandard2.0 and another .Net Framework multitagret nuget package.

### CODE REVIEW

**Comment by Dervall** [comment]
From what I can see, this looks good. I'll just have to fire this up and make sure that it works properly.

**Comment by harrison314** [comment]
II did not change Piglet source code (* .cs).

In recent commits i added XML documentation, configuration for pdb files and fix nuget Id.

Nuget crates using `dotnet pack -c Release`.

**Comment by davidaramant** [comment]
Any chance of this getting released soon? :)  Piglet's lexing speed still seems quite competitive from my benchmarks.

**Comment by jaxidian** [comment]
Just saw this used in a presentation. Neat stuff!!

**Comment by Dervall** [comment]
I know it took me 1,5 years. I'm really sorry for that. I'll make a release as well, so its migrated to netstandard in nuget for anyone thats using it.

**Pull request merged**
